### ISSUE TITLE
Modal for save, edit gist info, fork

### ISSUE THREAD

**Issue by drGrove** [lrvick/wearscript-playground#10]
@bwhite please elaborate

**Comment by bwhite** [comment]
If you perform a save (with keypress or otherwise) and
1.  it's the current user's gist, then save over it.  During the attempt it should indicate somewhere the status that it is saving possibly in a status bar or a small dedicated area for such things and indicate when it is successful or if it wasn't.
2. it's another user's gist, then we need to fork it, then save.  No modal necessary here either.
3. If it's a new gist then pop up a modal that has a secret/not secret checkbox, description (pre-filled with [wearscript]), and a textbox to enter in the name of the script (optional, if entered this creates a manifest.json file as per the current spec).  All of this is send to github.

Everything must use the wearscript gist api and should use the retry style that I do in my version, it basically keeps trying the commands until it gets a response.

**Comment by lrvick** [comment]
fixed in master.
