### ISSUE TITLE
Proper Gist, WS Client and Editor Services

### ISSUE THREAD

**Issue by drGrove** [lrvick/wearscript-playground#12]
@bwhite please elaborate

**Comment by bwhite** [comment]
Instead of having the logic for gists be inside the gist controller it should probably be in a service that is persistent and gets updates regularly or on manual refresh.  Editor should keep the state of the editor like "dirty" (content changed and not saved), current file, current gist, if it is the current user's gist (if not and we save we have to fork first), etc.

**Comment by drGrove** [comment]
So the plan is to set a socket event for on connect to allow for gists to have access to the socket.publish command. @lrvick feel free to elaborate

**Comment by bwhite** [comment]
Next to each gist have a shortcut button (small) to immediately load that script behind the scenes into the editor service and "wear the script".  Useful for mobile devices as a launcher.
