### ISSUE TITLE
JS Error to Code Map

### ISSUE THREAD

**Issue by drGrove** [lrvick/wearscript-playground#2]
@bwhite please elaborate

**Comment by bwhite** [comment]
If there is a problem in the JS code in angular now it's not practical to figure it out because of minification, @lrvick mentioned a way to fix that.

**Comment by bwhite** [comment]
I'm getting a few JS side bugs I can't diagnose because of minification

Uncaught TypeError: undefined is not a function d65e2569.vendor.js:20
(anonymous function) d65e2569.vendor.js:20
Uncaught Error: [$injector:modulerr] Failed to instantiate module wearscriptPlaygroundApp due to:
Error: [$injector:modulerr] Failed to instantiate module ngCsv due to:
Error: [$injector:nomod] Module 'ngCsv' is not available! You either misspelled...<omitted>...8)

**Comment by bwhite** [comment]
@lrvick  had mentioned using an html5 source map
http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/
https://github.com/mishoo/UglifyJS2

I'm stuck until I can fix whatever JS bug that is because it just clears the whole screen so I can't do anything.

**Comment by lrvick** [comment]
closed for inactivity
