### ISSUE TITLE
Integrate Head Cube JS/CSS into sensors

### ISSUE THREAD

**Issue by drGrove** [lrvick/wearscript-playground#6]
@bwhite please elaborate

**Comment by bwhite** [comment]
The old playground has a CSS cube that can rotate given head rotation.  We probably want a special button next to rotation vector in the sensor table (since it requires that).  Then pop it up in a modal or add it into the page in a way that looks nice.  Here is where I inject the code in the other playground https://github.com/wearscript/wearscript-android/blob/730a7c70e79ef5fb27ec77c8a01d5b0c890a96bb/server/js/playground.js#L112 and where I update it's position https://github.com/wearscript/wearscript-android/blob/730a7c70e79ef5fb27ec77c8a01d5b0c890a96bb/server/js/playground.js#L130
